// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: validation_codes.sql

package queries

import (
	"context"
)

const countValidationCodes = `-- name: CountValidationCodes :one
SELECT count(*) FROM validation_codes
`

func (q *Queries) CountValidationCodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countValidationCodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createValidaitonCode = `-- name: CreateValidaitonCode :one
INSERT INTO validation_codes(
  email, code
) VALUES (
  $1,$2
)

RETURNING id, code, email, use_at, created_at, updated_at
`

type CreateValidaitonCodeParams struct {
	Email string
	Code  string
}

func (q *Queries) CreateValidaitonCode(ctx context.Context, arg CreateValidaitonCodeParams) (ValidationCode, error) {
	row := q.db.QueryRowContext(ctx, createValidaitonCode, arg.Email, arg.Code)
	var i ValidationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.UseAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
