CREATE TABLE IF NOT EXISTS  users (
  id  SERIAL  PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 创建validation_codes表
CREATE TABLE  validation_codes(
  id SERIAL PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL,
  use_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
)

